### ISSUE TITLE
druid配置主从源，Mybatis plus join 不在自动启动，需要如何配置？

### ISSUE THREAD

**Issue by smypai** [yulichang/mybatis-plus-join#103]
### 当前使用版本(必填,否则不予处理)
<dependency>
    <groupId>com.baomidou</groupId>
    <artifactId>mybatis-plus-boot-starter</artifactId>
    <version>3.5.5</version>
</dependency>

<dependency>
    <groupId>com.github.yulichang</groupId>
    <artifactId>mybatis-plus-join-boot-starter</artifactId>
    <version>1.4.9</version>
</dependency>

<dependency>
    <groupId>mysql</groupId>
    <artifactId>mysql-connector-java</artifactId>
    <version>8.0.22</version>
</dependency>

<dependency>
    <groupId>com.alibaba</groupId>
    <artifactId>druid-spring-boot-starter</artifactId>
    <version>1.2.20</version>
</dependency>

@Configuration
public class DruidDataSourceConfig {

    @Bean
    public DruidDataSource routingDataSource() {
        DruidDataSource dataSource = new DruidDataSource();
        dataSource.setDriverClassName("com.mysql.cj.jdbc.Driver");
        dataSource.setUrl("jdbc:mysql://127.0.0.1:3306/demo?useUnicode=true&characterEncoding=utf8&useSSL=false&serverTimezone=UTC");
        dataSource.setUsername("root");
        dataSource.setPassword("root");
        return dataSource;
    }

    @Bean
    public DruidDataSource slaveDataSource1() {
        DruidDataSource dataSource = new DruidDataSource();
        dataSource.setDriverClassName("com.mysql.cj.jdbc.Driver");
        dataSource.setUrl("jdbc:mysql://127.0.0.1:3306/demo?useUnicode=true&characterEncoding=utf8&useSSL=false&serverTimezone=UTC");
        dataSource.setUsername("root");
        dataSource.setPassword("root");
        return dataSource;
    }

    @Bean
    public DruidDataSource slaveDataSource2() {
        DruidDataSource dataSource = new DruidDataSource();
        dataSource.setDriverClassName("com.mysql.cj.jdbc.Driver");
        dataSource.setUrl("jdbc:mysql://127.0.0.1:3306/demo?useUnicode=true&characterEncoding=utf8&useSSL=false&serverTimezone=UTC");
        dataSource.setUsername("root");
        dataSource.setPassword("root");
        return dataSource;
    }

    @Bean
    public AbstractRoutingDataSource routingDataSource(DruidDataSource masterDataSource, DruidDataSource slaveDataSource1) {
        Map<Object, Object> targetDataSources = new HashMap<>();
        targetDataSources.put("master", masterDataSource);
        targetDataSources.put("slave1", slaveDataSource1);
        targetDataSources.put("slave2", slaveDataSource2);

        AbstractRoutingDataSource routingDataSource = new AbstractRoutingDataSource() {
            @Override
            protected Object determineCurrentLookupKey() {
                if (TransactionSynchronizationManager.isActualTransactionActive()) {
                    // 如果有活动的事务，使用主数据库
                    return "master";
                } else {
                    // 否则，使用从数据库
                    // 这里只是简单地轮流使用从数据库，您可能需要根据实际情况实现更复杂的负载均衡策略
                    return ThreadLocalRandom.current().nextInt(2) == 0 ? "slave1" : "slave2";
                }
            }
        };
        routingDataSource.setTargetDataSources(targetDataSources);
        routingDataSource.setDefaultTargetDataSource(masterDataSource); // default is master
        return routingDataSource;
    }

    @Autowired
    @Qualifier("routingDataSource")
    private DataSource dataSource;

    @Bean
    public SqlSessionFactory sqlSessionFactory(MybatisPlusInterceptor mybatisPlusInterceptor, GlobalConfig globalConfig) throws Exception {
        MybatisSqlSessionFactoryBean sqlSessionFactoryBean = new MybatisSqlSessionFactoryBean();
        sqlSessionFactoryBean.setDataSource(dataSource);
        return sqlSessionFactoryBean.getObject();
    }
}
### 该问题是如何引起的？(确定最新版也有问题再提!!!)
druid配置主从源，Mybatis plus join 不在自动启动，需要如何配置？

### 报错信息
![image](https://github.com/yulichang/mybatis-plus-join/assets/7456405/827f5e08-3e9e-44a3-aab3-39de60830583)

**Comment by yulichang** [comment]
https://mybatisplusjoin.com/pages/problem.html#invalid-bound-statement-not-found
