### ISSUE TITLE
使用@FieldMapping注解映射查询 null

### ISSUE THREAD

**Issue by 203579397** [yulichang/mybatis-plus-join#112]
### 当前使用版本(必填,否则不予处理)

1.4.9

### 该问题是如何引起的？(确定最新版也有问题再提!!!)

使用@FieldMapping注解映射查询

### 报错信息

[
![微信截图_20240222155035](https://github.com/yulichang/mybatis-plus-join/assets/40386846/86e92cd6-d73a-4561-9644-5546318dfe47)
](url)

**Comment by yulichang** [comment]
1.4.11
