### ISSUE TITLE
请问MPJ是否支持MySQL5吗？

### ISSUE THREAD

**Issue by thinkcodee** [yulichang/mybatis-plus-join#113]
### 当前使用版本(必填,否则不予处理)
MP版本：3.5.3.2
MPJ版本：1.4.6

### 该问题是如何引起的？(确定最新版也有问题再提!!!)
请问MyBatis-Plus-Join是否支持MySQL5的版本？现在因为一些问题，服务器上的MySQL版本是5.X

**Comment by yulichang** [comment]
支持

**Comment by thinkcodee** [comment]
> 支持

好的，多谢，那我就放心了。
