### ISSUE TITLE
Caused by: org.apache.ibatis.ognl.OgnlException: nonEmptyOfWhere

### ISSUE THREAD

**Issue by pchao04** [yulichang/mybatis-plus-join#116]
### 当前使用版本(必填,否则不予处理)
mybatis-plus-boot-starter
3.5.2

### 该问题是如何引起的？(确定最新版也有问题再提!!!)

private MPJLambdaWrapper<JobShipment> getMpjWrapper() {
        return new MPJLambdaWrapper<JobShipment>()
                .select("top 1 JS_PK")
                .select(JobShipment::getJS_UniqueConsignRef,
                        JobShipment::getJS_HouseBill, JobShipment::getJS_OH_DeliveryAgent,
                        JobShipment::getJS_RL_NKLoadPort, JobShipment::getJS_RL_NKPlaceOfDischarge)
                .select(JobConsolTransport::getJW_Vessel, JobConsolTransport::getJW_VoyageFlight,
                        JobConsolTransport::getJW_ETD,JobConsolTransport::getJW_PL_NKCarrierServiceLevel)
                .select(JobContainer::getJC_ContainerCount)
                .select(RefContainer::getRC_Code)
                .select(JobConsol::getJK_OA_ShippingLineAddress, JobConsol::getJK_SystemLastEditUser,
                        JobConsol::getJK_UniqueConsignRef)
                .leftJoin(JobConShipLink.class, JobConShipLink::getJN_JS, JobShipment::getJS_PK)
                .leftJoin(JobConsol.class, JobConsol::getJK_PK, JobConShipLink::getJN_JK)
                .leftJoin(JobConsolTransport.class, on -> on
                        .eq(JobConsolTransport::getJW_ParentGUID, JobConsol::getJK_PK)
                        .eq(JobConsolTransport::getJW_LegOrder, "1")
                )
                .leftJoin(JobContainer.class, JobContainer::getJC_JK, JobConsol::getJK_PK)
                .leftJoin(RefContainer.class, RefContainer::getRC_PK, JobContainer::getJC_RC);
    }

### 报错信息

原始Exception
Caused by: org.apache.ibatis.ognl.OgnlException: nonEmptyOfWhere [java.lang.RuntimeException: java.lang.OutOfMemoryError: Java heap space]
Caused by: java.lang.RuntimeException: java.lang.OutOfMemoryError: Java heap space

**Comment by yulichang** [comment]
完整的报错信息
