### ISSUE TITLE
跨库表联查

### ISSUE THREAD

**Issue by suyuchuang** [yulichang/mybatis-plus-join#118]
### 当前使用版本(必填,否则不予处理)

1.4.11

### 该问题是如何引起的？(确定最新版也有问题再提!!!)
好像不支持跨库表联查，两个库都在同一个Mysql服务器上

### 重现步骤(如果有就写完整)
![image](https://github.com/yulichang/mybatis-plus-join/assets/43605897/436815eb-59d6-4b96-8db2-765965edbcdb)
![image](https://github.com/yulichang/mybatis-plus-join/assets/43605897/8f18d2fb-75d0-4c48-a961-4555fdb251ef)

### 报错信息
![image](https://github.com/yulichang/mybatis-plus-join/assets/43605897/52ad6895-8138-41a8-95e8-e09d8e0e0ccd)

**Comment by yulichang** [comment]
``` @TableName ``` 中设置数据库
