### ISSUE TITLE
升级到1.2.4 还是无法使用对应的plus-join下面的包

### ISSUE THREAD

**Issue by fibona** [yulichang/mybatis-plus-join#12]
org.apache.ibatis.binding.BindingException: Invalid bound statement (not found): com.xxx.mapper.IMailTemplateMapper.selectJoinList

启动时，我检查相关join包中的类都已经注入了
com.github.yulichang.config.InterceptorConfig中在sqlSessionFactoryList已经看到了mpjInterceptor

**Comment by fibona** [comment]
@Bean("sqlSessionFactory")
    @Primary
    public SqlSessionFactory sqlSessionFactory(@Autowired @Qualifier("dataSource") DataSource dataSource) throws Exception {

        MybatisSqlSessionFactoryBean sqlSessionFactoryBean = new MybatisSqlSessionFactoryBean();
        sqlSessionFactoryBean.setDataSource(dataSource);
        sqlSessionFactoryBean.setTypeAliasesPackage("com.xxx.core.entity");
        sqlSessionFactoryBean.setPlugins(paginationInterceptor());
        sqlSessionFactoryBean.setMapperLocations(new PathMatchingResourcePatternResolver().getResources("classpath:mappers/*.xml"));
        MybatisConfiguration configuration = new MybatisConfiguration();
        //查询结果为空的也返回
        configuration.setCallSettersOnNulls(true);
        //打开camel case 到下划线命名的映射
        configuration.setMapUnderscoreToCamelCase(true);
 
        sqlSessionFactoryBean.setConfiguration(configuration); 
        return sqlSessionFactoryBean.getObject();
    }

    @ConditionalOnMissingBean
    @Bean
    public PlatformTransactionManager transactionManager(DataSource dataSource) {
        return new DataSourceTransactionManager(dataSource);
    }

    /**
     * 分页插件 
     */
    @Bean
    public MybatisPlusInterceptor paginationInterceptor() {
        MybatisPlusInterceptor interceptor = new MybatisPlusInterceptor();
        PaginationInnerInterceptor paginationInterceptor = new PaginationInnerInterceptor();
        paginationInterceptor.setMaxLimit((long) Integer.MAX_VALUE); 
        interceptor.addInnerInterceptor(paginationInterceptor);
        return interceptor;
    }

**Comment by Chen491733492** [comment]
我也是的

**Comment by Chen491733492** [comment]
请问 有解决了吗

**Comment by yulichang** [comment]
```java
@Configuration
public class MybatisPlusConfig {

    /**
     * 关联SqlSessionFactory与GlobalConfig
     * 设置mybatis 拦截器
     */
    @Bean
    public SqlSessionFactory sqlSessionFactory(DataSource dataSource)  {
        MybatisSqlSessionFactoryBean sessionFactory = new MybatisSqlSessionFactoryBean();
        sessionFactory.setDataSource(dataSource);
        // 关联SqlSessionFactory与GlobalConfig
        sessionFactory.setGlobalConfig(new GlobalConfig().setSqlInjector(new MPJSqlInjector()));
        // 添加拦截器 MPJInterceptor需要放在最后面
        // 如果项目没有使用拦截器, 只需要添加MPJ拦截器sessionFactory.setPlugins(new MPJInterceptor());
        sessionFactory.setPlugins(你的拦截器, new MPJInterceptor());
        // 其他配置 略
        return sessionFactory.getObject();
    }
}
```
