### ISSUE TITLE
同时设置setEntity和setAlias时生成的sql有误

### ISSUE THREAD

**Issue by Arowa-Z** [yulichang/mybatis-plus-join#120]
### 当前使用版本(必填,否则不予处理)
1.4.11

### 该问题是如何引起的？(确定最新版也有问题再提!!!)
当使用 MPJLambdaWrapper(T entity, String alias) api时，如果 alias 不为 ConfigProperties.tableAlias 的值时，由 entity 生成的 where 条件 依旧是 ConfigProperties.tableAlias，而 select 中的字段却是 传入的 alias 

### 重现步骤(如果有就写完整)
代码：
![image](https://github.com/yulichang/mybatis-plus-join/assets/18597375/82c258aa-23f9-4c57-b72b-db2a84032079)

### 报错信息
sql错误部分：
![image](https://github.com/yulichang/mybatis-plus-join/assets/18597375/ef5cb984-c726-4c31-8795-dba1ccaddc01)

通过查看生成的xml，判断为根据 entity 所生成的条件表别名写死为  ConfigProperties.tableAlias 的值，未替换为${ew.alias}
![image](https://github.com/yulichang/mybatis-plus-join/assets/18597375/ae7ee65a-60d1-4424-935d-fae33a345dde)

**Comment by qichangleixin** [comment]
请问下自动生成的xml怎么查看的啊

**Comment by Arowa-Z** [comment]
> 请问下自动生成的xml怎么查看的啊

在对应的`injectMappedStatement`方法里打断点
![image](https://github.com/yulichang/mybatis-plus-join/assets/18597375/a68abae9-fd76-463f-b7fa-c9b542787e40)

**Comment by yulichang** [comment]
升级版本
