### ISSUE TITLE
MPJLambdaWrapper能新增一个支持可变参数叫noSelect的方法吗

### ISSUE THREAD

**Issue by Lizehangz** [yulichang/mybatis-plus-join#124]
### 当前使用版本(必填,否则不予处理)
1.4.11

**Comment by Lizehangz** [comment]
join查询的时候 不能选择说查join的那张表的部分字段 我尝试了select 但是还是全查出来了

**Comment by tanpenggood** [comment]
noSelect的含义是什么呢 应用场景可以列举一下吗
可变参数的参数数据类型是什么？

**Comment by Lizehangz** [comment]
> noSelect的含义是什么呢 应用场景可以列举一下吗 可变参数的参数数据类型是什么？

MPJLambdaWrapper原本不是有个名为select的方法用来指定需要查询的字段吗？但是有些时候表中需要查询的字段很多，但是又不想全部查询出来，就要给select这个方法传递很长的一串参数。正常来说的话这个问题会用创建不同的视图对象来解决，但是会导致存在很多视图对象，所以想要有个noSelect方法来指定不查询的字段。select方法接收的不就是可变参数或者叫可变长参数吗？noSelect需要传递的参数数据类型和select方法的参数数据类型一样。

**Comment by tanpenggood** [comment]
已经有类似功能的pr了，期待merge吧

https://github.com/yulichang/mybatis-plus-join/pull/80
