### ISSUE TITLE
left join查询如何添加多个查询条件

### ISSUE THREAD

**Issue by wencong20ziji** [yulichang/mybatis-plus-join#130]
### 当前使用版本(必填,否则不予处理)
1.4.5

### 该问题是如何引起的？(确定最新版也有问题再提!!!)
查看官方文档没有体现

### 重现步骤(如果有就写完整)
select * from ORDER_INFO oi 
left join ORDER_ITEM oii on oii.order_id = oi.id and oii.order_id = '123'

**Comment by yulichang** [comment]
https://www.mybatisplusjoin.com/pages/core/lambda/join/leftJoin.html#%E5%A4%9A%E6%9D%A1%E4%BB%B6%E7%A4%BA%E4%BE%8B
