### ISSUE TITLE
多租户开启后，主表租户ID位置错了

### ISSUE THREAD

**Issue by Liu3334** [yulichang/mybatis-plus-join#133]
### 当前使用版本(必填,否则不予处理)
1.4.12

### 该问题是如何引起的？(确定最新版也有问题再提!!!)
![image](https://github.com/yulichang/mybatis-plus-join/assets/53702199/5b476593-8bde-44a0-ac58-1dede6817ad6)

**Comment by yulichang** [comment]
代码以及插件是如何配置的？
