### ISSUE TITLE
mybatis-plus-join-core-1.4.12.jar 用owasp maven插件检查，怀疑误报高危安全漏洞

### ISSUE THREAD

**Issue by iweco** [yulichang/mybatis-plus-join#134]
### 当前使用版本(必填,否则不予处理)
mybatis-plus-join-boot-starter 1.4.12 

### 该问题是如何引起的？(确定最新版也有问题再提!!!)
mybatis-plus-join-core-1.4.12.jar 报了高危安全漏洞

### 重现步骤(如果有就写完整)
![image](https://github.com/yulichang/mybatis-plus-join/assets/67083131/806352a9-a036-4de1-afbf-ca126cd6927d)

### 报错信息
![image](https://github.com/yulichang/mybatis-plus-join/assets/67083131/306bcafe-8216-4690-9f5f-a30802991576)

**Comment by yulichang** [comment]
这是mybstis plus的吧
