### ISSUE TITLE
leftjoin分页查询问题, 查询有数据, 但是records是All elements are null 

### ISSUE THREAD

**Issue by qq243329721** [yulichang/mybatis-plus-join#139]
### 当前使用版本(必填,否则不予处理)
            <dependency>
                <groupId>com.github.yulichang</groupId>
                <artifactId>mybatis-plus-join-core</artifactId>
                <version>1.4.12</version>
            </dependency>
### 该问题是如何引起的？(确定最新版也有问题再提!!!)
 MPJLambdaWrapper<StationGas> query = new MPJLambdaWrapper<>();
 query.selectAll(StationGas.class);
 query.selectCollection(StationGasGun.class, StationGas::getStationGasGunList);
 query.leftJoin(StationGasGun.class, StationGasGun::getStationGasId, StationGas::getId);
 query.eq(StationGasGun::getType, 1);
 Page<StationGas> iPage =  this.stationGasService.selectJoinListPage(selectPage, StationGas.class, query);
![image](https://github.com/yulichang/mybatis-plus-join/assets/78414175/3794b392-1f14-45e9-98ea-9b926fd99904)

 query.selectCollection(StationGasGun.class, StationGas::getStationGasGunList);
 query.leftJoin(StationGasGun.class, StationGasGun::getStationGasId, StationGas::getId);
 query.eq(StationGasGun::getType, 1);
不加这三行的时候时候返回正常
![image](https://github.com/yulichang/mybatis-plus-join/assets/78414175/0970ea52-2af3-47e5-a25f-ea5ce77a0b5a)

### 重现步骤(如果有就写完整)

同上

### 报错信息

无报错

**Comment by qq243329721** [comment]
![image](https://github.com/yulichang/mybatis-plus-join/assets/78414175/d9ade2a4-ea34-43cc-b8ee-449f46f69d79)
补充, 带leftjoin条件 selectJoinList也是null

**Comment by yulichang** [comment]
依赖能用starter

**Comment by cxz158** [comment]
我也同样遇到了records返回都是null的情况，这个错误可能是因为自定义sqlSessionFactory导致的，我引用的mybatis-plus-join-boot-starter但可能因为公司组件自定义的sqlSessionFactory影响了MPJInterceptor的添加，手动配置最后一个添加MPJInterceptor后正常了。
https://mybatisplusjoin.com/pages/problem.html#invalid-bound-statement-not-found
