### ISSUE TITLE
两种list方法结果不一样

### ISSUE THREAD

**Issue by 203579397** [yulichang/mybatis-plus-join#141]
### 当前使用版本(必填,否则不予处理)

1.4.12

### 该问题是如何引起的？(确定最新版也有问题再提!!!)

![微信截图_20240522114748](https://github.com/yulichang/mybatis-plus-join/assets/40386846/31d4976e-9c8d-4856-90d8-e7145dae34ea)

### 重现步骤(如果有就写完整)

lazy-initialization: true 的时候出现该情况

**Comment by yulichang** [comment]
能提供复现工程吗
