### ISSUE TITLE
升级版本后日志输出异常

### ISSUE THREAD

**Issue by ehehe066** [yulichang/mybatis-plus-join#148]
### 当前使用版本(必填,否则不予处理)
mybatis-plus-join-boot-starter 1.4.13
mybatis-plus-boot-starter 3.5.7

### 该问题是如何引起的？(确定最新版也有问题再提!!!)
mybatis-plus-join-boot-starter从1.4.8.1 升级 至 1.4.13后日志输出出现异常
本来简洁的日志 变成 全部都是字段的重复输出了2次
![3](https://github.com/yulichang/mybatis-plus-join/assets/30278102/c0472326-3f09-4175-b3d9-18588e343d99)
![4](https://github.com/yulichang/mybatis-plus-join/assets/30278102/c3064e6a-6a3b-402d-bb3c-220c8d6d82d6)

### 重现步骤(如果有就写完整)
版本升级后日志输出样式就不一样了
降级回1.4.8.1就恢复成原来的样子  升级一个小版本到1.4.9就又输出异常了

**Comment by ehehe066** [comment]
![6](https://github.com/yulichang/mybatis-plus-join/assets/30278102/72e4970b-1234-42b4-b820-571013cee190)
![7](https://github.com/yulichang/mybatis-plus-join/assets/30278102/310f89b5-5696-4c63-bc06-05120f402db0)
是这个id被当成clazz输出了

**Comment by yulichang** [comment]
好的，下个版本修复
