### ISSUE TITLE
EntityMapping注解能不能增加支持多个字段

### ISSUE THREAD

**Issue by flylink888** [yulichang/mybatis-plus-join#150]
### 当前使用版本(必填,否则不予处理)

1.4.5

### 该问题是如何引起的？(确定最新版也有问题再提!!!)

    @TableField(exist = false)
    @EntityMapping(thisField = Fields.supplierCode,joinField = SrmSupplier.Fields.supplierCode)
    private SrmSupplier srmSupplier;
SrmSupplier需要通过组合主键supplierCode+companyCode来关联,如果能够EntityMapping注解能不能增加支持多个字段
就好了,用condition或apply来实现也可以.
目前condition或apply的value值不能指定Fields.companyCode

**Comment by yulichang** [comment]
不支持
