### ISSUE TITLE
selectJoinCount对union表查询，只是count了第一张表

### ISSUE THREAD

**Issue by andy1199** [yulichang/mybatis-plus-join#156]
### 当前使用版本(必填,否则不予处理)
1.4.13

### 重现步骤(如果有就写完整)
@Test
    void 测试selectCount() {
        MPJLambdaWrapper<User> wrapper = JoinWrappers.lambda(User.class);
        wrapper.select(User::getId);

        MPJLambdaWrapper<T2> wrapper1 = JoinWrappers.lambda(T2.class);
        wrapper1.selectAs(T2::getColumn_1, User::getId);
        wrapper.union(wrapper1);
        List<Map<String, Object>> list = userMapper.selectJoinMaps(wrapper);
        System.out.println(list.size());  //结果正确  SELECT t.id FROM user t UNION SELECT t.column_1 AS id FROM t2 t

        System.out.println(userMapper.selectJoinCount(wrapper));  //结果错误  SELECT COUNT( t.id ) FROM user t
    }

**Comment by yulichang** [comment]
selectJoinCount本就不考虑支持union
可以分开调用selectJoinCount再计算或者写sql
