### ISSUE TITLE
selectJoinMapsPage 多表查询分页数量不准确

### ISSUE THREAD

**Issue by thebestKaKa** [yulichang/mybatis-plus-join#157]
### 当前使用版本(必填,否则不予处理)

1.4.11

### 该问题是如何引起的？(确定最新版也有问题再提!!!)
多表联查，使用分页方法selectJoinMapsPage

### 重现步骤(如果有就写完整)
详见：
![image](https://github.com/user-attachments/assets/1266c101-0b6a-4220-9c0f-b3b35000ca1b)

### 报错信息
查询结果与实际数量对不上
![image](https://github.com/user-attachments/assets/731e41e7-9e67-4198-b541-e00e415da4aa)
实际结果：
![image](https://github.com/user-attachments/assets/7b15c260-01b3-4ef1-8cb8-2caab7871077)

**Comment by yulichang** [comment]
看sql日志

**Comment by qq61966100** [comment]
看起来和我的问题差不多，假如有个user表，有个order表，那么我想以user表作为分页基础，查询出来的是userlist，然后order嵌套在每个user对象里面，因为sql查出来leftjoin会导致数据数量根据具体的order数量来，所以总数不对，我尝试使用groupby，不过聚合函数不知道应该怎么写？或者作者有没有其他好方法？

**Comment by liuyuanting1209** [comment]
SELECT COUNT(*) AS total
FROM tb_biz_deposit t
WHERE (t.create_date >= ? AND t.create_date <= ?)

SELECT t.id,
       t.user_id,
       t.order_no,
       t.apply_amount,
       t.approve_amount,
       t.bank,
       t.bank_no,
       t.status,
       t.payment_date,
       t.updater,
       t.update_date,
       t.creator,
       t.create_date,
       own.real_name     AS userName,
       creator.real_name AS creatorName,
       updater.real_name AS updaterName
FROM tb_biz_deposit t
         LEFT JOIN tb_user own ON (own.id = t.user_id)
         LEFT JOIN tb_user creator ON (creator.id = t.creator)
         LEFT JOIN tb_user updater ON (updater.id = t.updater)
WHERE (t.create_date >= ? AND t.create_date <= ?)
ORDER BY t.create_date DESC
LIMIT ?

我也碰到这个问题了，获取count(*) 没有考虑join

**Comment by yulichang** [comment]
> 选择 COUNT（*） 作为 tb_biz_deposit T 的总数，其中 （t.create_date >= ？和 t.create_date <= ？）
> 
> SELECT t.id， t.user_id， t.order_no， t.apply_amount， t.approve_amount， t.bank， t.bank_no， t.status， t.payment_date， t.updater， t.update_date， t.creator， t.create_date， own.real_name AS userName， creator.real_name AS creatorName， updater.real_name AS updaterName FROM tb_biz_deposit t左联接 tb_user 自己的 ON （own.id = t.user_id） 左联接 tb_user creator ON （creator.id = t.creator） 左联接 tb_user updater ON （updater.id = t.updater） 其中 （t.create_date >= ？和 t.create_date <= ？）按 t.create_date DESC LIMIT 排序 ？
> 
> 我也碰到这个问题了，获取count（*） 没有考虑join

https://baomidou.com/plugins/pagination/#page-%E7%B1%BB
