### ISSUE TITLE
@TableField注解的typeHandler类型处理器泛型失效

### ISSUE THREAD

**Issue by superxiao** [yulichang/mybatis-plus-join#163]
### 当前使用版本(必填,否则不予处理)
1.4.13

### 该问题是如何引起的？(确定最新版也有问题再提!!!)
https://github.com/yulichang/mybatis-plus-join/issues/127 已经修复了这个问题，但是在mybatis plus后续更新后修复应该是失效了。

### 重现步骤(如果有就写完整)
创建一个List\<A\>类型field，A是一个用Jackson标注过的pojo类型。field带有mybatis plus的JacksonTypeHandler的标注（该handler目前只支持postgres读，不支持写）。数据库对应posgres json或者jsonb类型，内容是包含json object的列表（e.g. [{"prop": 1}, {"prop": 2}], prop是A的field name）。通过selectJoinList之类方法把json map到List\<A\>.

### 报错信息
会创建List\<TreeMap\>而不是List\<A\>

原因是

https://github.com/yulichang/mybatis-plus-join/blob/master/mybatis-plus-join-core/src/main/java/com/github/yulichang/wrapper/segments/SelectCache.java#L95
这里
`this.typeHandlerClass = tableFieldInfo.getTypeHandler();`
可能要改成
`this.typeHandlerClass = tableFieldInfo.getResultMapping().getTypeHandler();`

前者不带有效泛型，后者带[有效泛型](https://github.com/baomidou/mybatis-plus/blob/3.0/mybatis-plus-core/src/main/java/com/baomidou/mybatisplus/core/metadata/TableFieldInfo.java#L567)。

**Comment by qichhhhh** [comment]
同样遇到该问题了，selectJoinList 之后 DTO 中定义的字段 List<XXX> 被序列化成了 List<JSONObject>

**Comment by qichhhhh** [comment]
@yulichang  很好复现，麻烦看一下

**Comment by yulichang** [comment]
> @yulichang 很好复现，麻烦看一下

好的

**Comment by superxiao** [comment]
我刚发现`getResultMapping`这个方法是protected, 这不知道怎么修呢。。。
