### ISSUE TITLE
selectCollection 分页问题

### ISSUE THREAD

**Issue by 404-pp** [yulichang/mybatis-plus-join#167]
### 当前使用版本(必填,否则不予处理)

1.4.13

### 该问题是如何引起的？(确定最新版也有问题再提!!!)

selectCollection 分页总数有问题

### 报错信息

selectCollection 在分页情况下无法使用，请问后续版本有规划解决吗

**Comment by yulichang** [comment]
无解

**Comment by 404-pp** [comment]
请问像pg 递归常使用的CTE可以实现吗
