### ISSUE TITLE
希望leftjoin同一个表的时候，别名可以不重复，或者允许自定义别名

### ISSUE THREAD

**Issue by dekmas** [yulichang/mybatis-plus-join#18]
我这条sql会报错，因为别名重复，连接了两次sys_dictionary表，但是别名都是一样的
`IPage<HiddenTroubleVo> page = hiddenTroubleMapper.selectJoinPage(
                new Page<HiddenTroubleVo>(param.getPage(), param.getLimit()),
                HiddenTroubleVo.class,
                new MPJLambdaWrapper<HiddenTrouble>()
                        .selectAll(HiddenTrouble.class)
                        .selectAs(SysDictionary::getName, HiddenTroubleVo::getTypeName)
                        .selectAs(User::getName, HiddenTroubleVo::getCreateUserName)
                        .selectAs(SysDictionary::getName, HiddenTroubleVo::getStatusName)
                        .leftJoin(SysDictionary.class, (on) ->
                                on.eq(SysDictionary::getValue, HiddenTrouble::getType)
                                        .eq(SysDictionary::getType, SysDictionaryType.HIDDEN_TROUBLE_TYPE)
                        )
                        .leftJoin(User.class, User::getId, HiddenTrouble::getCreateUser)
                        .leftJoin(ServiceAgency.class, ServiceAgency::getId, HiddenTrouble::getServiceAgencyId)
                        .leftJoin(SysDictionary.class, (on) ->
                                on.eq(SysDictionary::getValue, HiddenTrouble::getType)
                                        .eq(SysDictionary::getType, SysDictionaryType.HIDDEN_TROUBLE_STATUS)
                        )
        );`

**Comment by wendiaoxu** [comment]
同问题

**Comment by LouisLiu00** [comment]
同问题

**Comment by yulichang** [comment]
升级版本
https://mybatisplusjoin.com/pages/core/lambda/join/leftJoin.html
