### ISSUE TITLE
[功能改进]: 描述 升级mybatis.plus.version 3.5.8版本什么时候发布？

### ISSUE THREAD

**Issue by jaimyjie** [yulichang/mybatis-plus-join#204]
### 确认

- [X] 我的版本是最新版本, 我的版本号与 [version](https://central.sonatype.com/search?q=g:com.github.yulichang%20%20a:mybatis-plus-join-boot-starter&smo=true) 相同, 并且项目里无依赖冲突
- [X] 我已经在 [issue](https://github.com/yulichang/mybatis-plus-join/issues) 中搜索过, 确认问题没有被提出过
- [X] 我已经修改标题, 将标题中的 描述 替换为遇到的问题

### 功能改进

升级mybatis.plus.version 3.5.8版本什么时候发布？1.5版本用的还是3.5.7哦

**Comment by yulichang** [comment]
1.5.0支持3.5.8
