### ISSUE TITLE
引入之后，原有的方法报错，大佬帮看看

### ISSUE THREAD

**Issue by lxy180** [yulichang/mybatis-plus-join#21]
"程序错误|doDispatch(DispatcherServlet.java:1053)|Handler dispatch failed; nested exception is java.lang.AbstractMethodError: com.github.yulichang.interceptor.MPJInterceptor.plugin(Ljava/lang/Object;)Ljava/lang/Object;"

**Comment by yulichang** [comment]
mybatis 版本个 mybatis plus 版本不匹配
