### ISSUE TITLE
[错误报告]: 连表查询时，SQL语句里没有给表设置默认别名，但是字段设置了别名，导致SQL报错。

### ISSUE THREAD

**Issue by gordon-lang** [yulichang/mybatis-plus-join#214]
### 确认

- [X] 我的版本是最新版本, 我的版本号与 [version](https://central.sonatype.com/search?q=g:com.github.yulichang%20%20a:mybatis-plus-join-boot-starter&smo=true) 相同, 并且项目里无依赖冲突
- [X] 我已经在 [issue](https://github.com/yulichang/mybatis-plus-join/issues) 中搜索过, 确认问题没有被提出过
- [X] 我已经修改标题, 将标题中的 描述 替换为遇到的问题

### 当前程序版本

1.5.1

### 问题描述

我的serviceImpl里的查询代码如下：
` List<Map<String, Object>> maps = houseMapper.selectMaps(
                new MPJLambdaWrapper<ConfigHouse>()
                        .select(ConfigHouse::getId, ConfigHouse::getName)
                        .selectAs(ConfigBuilding::getName, "buildingName")
                        .leftJoin(ConfigBuilding.class, ConfigBuilding::getId, ConfigHouse::getBuildingId)
                        .eq(ConfigHouse::getId, "1846754161923682305"));`
使用MPJLambdaWrapper进行连表查询，查询语句里对字段设置了“t”的别名，但是表没有给别名，不知道什么原因，然后只能SQL报错，下面控制台执行日志也打印了“SELECT t.id,t.name,t1.NAME AS buildingName FROM config_house WHERE (t.id = ?)”，令人费解；

### 详细堆栈日志

```bash
14:49:19.895 [http-nio-8097-exec-1] INFO  o.a.c.c.C.[.[.[/] - [log,173] - Initializing Spring DispatcherServlet 'dispatcherServlet'
14:49:20.546 [http-nio-8097-exec-1] DEBUG c.s.b.m.C.selectMaps - [debug,137] - ==>  Preparing: SELECT t.id,t.name,t1.NAME AS buildingName FROM config_house WHERE (t.id = ?)
14:49:20.547 [http-nio-8097-exec-1] DEBUG c.s.b.m.C.selectMaps - [debug,137] - ==> Parameters: 1846754161923682305(String)
```

**Comment by yulichang** [comment]
使用selectJoinMaps
