### ISSUE TITLE
想问一下如下一个三表查询的场景如何构造返回DTO才能接收正确

### ISSUE THREAD

**Issue by Fantast416** [yulichang/mybatis-plus-join#25]
有如下三张表且关系如下：
Teacher <----一对多----> User<----多对一----->Class
现在想要知道某个teacherId老师下所有学生的信息以及各个学生的班级名称，我使用如下wrapper
MPJLambdaWrapper wrapper = new MPJLambdaWrapper<SealDataset>()
                .selectAll(Teacher.class)
                .select(Class::getClassName)
                .selectCollection(User.class,ResDTO::getUserList)
                .leftJoin(User.class, User::getUserId, Teacher::getUserId)
                .leftJoin(Class.class,Class::getClassId,SealAuditTask::getClassId)
                .eq(Teacher::getTeacherId,teacherId);
teacherMapper.selectJoinOne(ResDTO.class,wrapper);
这样子的话，通过日志看到SQL语句确实能够正确执行，且班级名称ClassName也返回了，但是由于不知道如何定义ResDTO所以返回的ResDTO对象中并没有这个属性，怎么加都没法注入，希望看看。
目前的ResDTO如下：
@Data
public class ResDTO {
    private Integer teacherId;
    private List<User> users;
}

**Comment by yvdeshuai** [comment]
我也有这个问题，请问大佬解决这个问题了吗

**Comment by yvdeshuai** [comment]
okk啦，今天解决了这个问题。我是使用MPJLambdaWrapper的selectCollection帮助我快速将连表查询的结果中的两个对象聚合成一个新的对象，这三个对象分别是①customer:`    private Long customerId;
    private String customerName;`,②order：`private Long orderId;
    private Long customerId;`，③OrderWithCustomer：`    private List<Order> order;

    private List<Customer> customer;`。在联表查询结果中包含customer和order对象，customer和order是多对多关系，把查询结果转成OrderWithCustomer类型的代码如下：`MPJLambdaWrapper<Order> queryWrapper = JoinWrappers.lambda(Order.class)
                .selectCollection(Order.class,OrderWithCustomer::getOrder)
                .selectCollection(Customer.class,OrderWithCustomer::getCustomer);`注意记得符合MPJLambdaWrapper官网上的版本和mapper文件继承即可，初学者，技术不精，拙见

**Comment by yvdeshuai** [comment]
okk啦，今天解决了这个问题。我是使用MPJLambdaWrapper的selectCollection帮助我快速将连表查询的结果中的两个对象聚合成一个新的对象，这三个对象分别是①customer:    private Long customerId; private String customerName;,②order：private Long orderId; private Long customerId;，③OrderWithCustomer：` private List order ;private List<Customer> customer;`
在联表查询结果中包含customer和order对象，customer和order是多对多关系，把查询结果转成OrderWithCustomer类型的代码如下：
`MPJLambdaWrapper<Order> queryWrapper = JoinWrappers.lambda(Order.class)
            .selectCollection(Order.class,OrderWithCustomer::getOrder)
            .selectCollection(Customer.class,OrderWithCustomer::getCustomer);`注意记得符合MPJLambdaWrapper官网上的版本和mapper文件继承即可，初学者，技术不精，拙见

**Comment by Fantast416** [comment]
可以可以，我后来直接用两次查询了，没做三表联查
