### ISSUE TITLE
同时使用【一对多查询、多对一查询】，最后还要【分页查询】

### ISSUE THREAD

**Issue by 0501wenjie** [yulichang/mybatis-plus-join#33]
这种情况有办法处理吗？

**Comment by yulichang** [comment]
没办法, 对多查询和分页插件是不支持的, 
由于嵌套结果方式会导致结果集被折叠，因此分页查询的结果在折叠后总数会减少，所以无法保证分页结果数量正确。

**Comment by yulichang** [comment]
只能自己写sql, 或拆成多次单表查询, 然后组装数据

**Comment by longge125521** [comment]
<img width="729" alt="image" src="https://github.com/yulichang/mybatis-plus-join/assets/20812326/45b33d56-513a-4c84-881a-b7a792df2d77">
也没有可能以后实现这种, 填充Blist通过返回的B的id集合再次查询b表数据然后填充,  因为实际业务中的数据量很大, 一般都需要分页, 上面说的只能自己写sql, 或拆成多次单表查询, 然后组装数据, 这个步骤能不能也通用起来, 如果能实现这个功能, 感觉还是很有场景的, 希望大佬关注
