### ISSUE TITLE
selectJoinPage在日志能看到获取到数据，但records看不到查询结果

### ISSUE THREAD

**Issue by tom055** [yulichang/mybatis-plus-join#38]
你好 请问 我已经查询到数据但records中数据是空的
![捕获](https://user-images.githubusercontent.com/17687356/227725341-c627de25-9421-4961-b80c-263bd0649110.PNG)
![捕获2](https://user-images.githubusercontent.com/17687356/227725345-1fa14438-1a76-4dfb-bf65-f4098796d7d5.PNG)
![捕获3](https://user-images.githubusercontent.com/17687356/227725346-1895d3df-9d2c-4037-9233-5be69261798c.PNG)
![捕获4](https://user-images.githubusercontent.com/17687356/227725347-5461c82a-7f4d-4c86-94b1-d085362fb034.PNG)

**Comment by yulichang** [comment]
你的项目应该是自定义了sqlSessionFactory，没有添加MPJ的拦截器
factory.setPlugins(你的拦截器，new MPJInterceptor())

**Comment by tom055** [comment]
非常感谢 已解决~~~
