### ISSUE TITLE
Predicate过滤i -> i.getFieldFill() == FieldFill.DEFAULT未返回主键ID

### ISSUE THREAD

**Issue by sunxy** [yulichang/mybatis-plus-join#40]

**Comment by yulichang** [comment]
不带id, 延用的是mp的逻辑
mp的LambdaQueryWrapper的select过滤也是不含主键的

**Comment by sunxy** [comment]
使用mp的LambdaQueryWrapper会返回ID的，它在chooseSelect中拼接了主键ID，我在很多项目中都已经使用过的。
------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "yulichang/mybatis-plus-join"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2023年3月31日(星期五) 晚上8:09
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [yulichang/mybatis-plus-join] Predicate过滤i -&gt; i.getFieldFill() == FieldFill.DEFAULT未返回主键ID (Issue #40)





 
不带id, 延用的是mp的逻辑
 mp的LambdaQueryWrapper的select过滤也是不含主键的

**Comment by yulichang** [comment]
用 selectFilter
