### ISSUE TITLE
多个条件构造器使用，报空指针问题

### ISSUE THREAD

**Issue by HELLFS** [yulichang/mybatis-plus-join#43]
连表查询时，多个条件构造器连续使用condition参数来控制SQL是否拼接，当condition参数传入 对布尔包装类型参数的null判断 会出现空指针异常问题，还有LocalDateTime数组 对象 null值判断 ，其他类型暂未出现

关键代码如图：
![image](https://github.com/yulichang/mybatis-plus-join/assets/58764900/c91b893f-ce76-448b-a5f7-dd99f4b84803)

选中的参数 都是默认值，走到选中参数对应的条件构造器时就会报空指针问题 这种情况

**Comment by yulichang** [comment]
https://gitee.com/baomidou/mybatis-plus/issues/I5GG9C
