### ISSUE TITLE
无法将自定义字符串查询到的结果映射到实体类

### ISSUE THREAD

**Issue by undoubted** [yulichang/mybatis-plus-join#54]
使用以下方法可以查询到结果，但是无法映射到实体类
比如：
 `select("t.id")`
`select("t.id as tid")`
`selectAs("t.id", DTO::getDtoId)`

而以下方法是可以的
`select(PO::getId)`
`selectAs(PO::getId, DTO::getDtoId)`

看起来是 `SelectString` 的问题？

**Comment by yulichang** [comment]
你用的是那个版本 
完整的wrapper代码可以看一下吗

**Comment by undoubted** [comment]
发现只要有 `selectAssociation` 就会出现问题
```
@Data
public class User {
    private Integer id;
    private String name;
}

@Data
public class Topic {
    private Long id;
    private Long userId;
    private String content;
}

@Data
public class UserDto {
    private Long id;
    private String name;
}

@Data
public class TopicDto {
    private Long id;
    private UserDto user;
    private String content;
    private Long uid;
}

MPJLambdaWrapper<Topic> wrapper = MPJWrappers.<Topic>lambdaJoin()
    .selectAll(Topic.class)
    .selectAssociation("user", User.class, TopicDto::getUser) // 注释掉这里，就能取到uid
    .select("user.id as uid")
    .leftJoin(User.class, "user", User::getId, Topic::getUserId);
List<TopicDto> topics = topicDao.selectJoinList(TopicDto.class, wrapper);
```

**Comment by telAsOne** [comment]
> 你用的是那个版本 完整的wrapper代码可以看一下吗

同样的1.4.5 也出现了相同的问题，使用子查询正常可以返回，但加了selectAssociation或者selectCollection，子查询定义的别名就无法映射值（日志显示是有值的）
wrapper.selectSub(BhApply.class, w -> w.selectCount(BhApply::getBatch)
                    .eq(BhBatch::getId, BhApply::getBatch)
                    .in(BhApply::getStatus,applyStatusList), BhBatchVo::getTotalApply); // 正常这样 查询能返回，加上下面的就不行了

wrapper.selectAssociation(AuditOpinionBatch.class, BhBatchVo::getAuditOpinionBatchList);
wrapper.leftJoin(AuditOpinionBatch.class, on -> on.eq(AuditOpinionBatch::getBatchId,BhBatch::getId).eq(AuditOpinionBatch::getStatus,status));


// 查询
Page<BhBatchVo> bhBatches = this.baseMapper.selectJoinPage(page,BhBatchVo.class,wrapper);

这样拼接的sql能查到totalApply的值，就是无法映射

// 使用Map接收是可以的
Page page1 = this.baseMapper.selectJoinMapsPage(page, wrapper);

**Comment by jianhao2010303** [comment]
+1

**Comment by undoubted** [comment]
> 发现只要有 `selectAssociation` 就会出现问题。 用的最新版1.4.5
> 
> ```
> @Data
> public class User {
>     private Integer id;
>     private String name;
> }
> 
> @Data
> public class Topic {
>     private Long id;
>     private Long userId;
>     private String content;
> }
> 
> @Data
> public class UserDto {
>     private Long id;
>     private String name;
> }
> 
> @Data
> public class TopicDto {
>     private Long id;
>     private UserDto user;
>     private String content;
>     private Long uid;
> }
> 
> MPJLambdaWrapper<Topic> wrapper = MPJWrappers.<Topic>lambdaJoin()
>     .selectAll(Topic.class)
>     .selectAssociation("user", User.class, TopicDto::getUser) // 注释掉这里，就能取到uid
>     .select("user.id as uid")
>     .leftJoin(User.class, "user", User::getId, Topic::getUserId);
> List<TopicDto> topics = topicDao.selectJoinList(TopicDto.class, wrapper);
> ```

发现加了alias的selectAs也获取不到uid
```
MPJLambdaWrapper<Topic> wrapper = MPJWrappers.<Topic>lambdaJoin()
    .selectAll(Topic.class)
    .selectAssociation("user", User.class, TopicDto::getUser)
    .select("user.id as uid")                       // 获取不到uid
    .selectAs("user", User::getId, Topic::getUid)   // 获取不到uid
    .selectAs(User::getId, Topic::getUid)           // 可以获取到uid
    .leftJoin(User.class, "user", User::getId, Topic::getUserId);
List<TopicDto> topics = topicDao.selectJoinList(TopicDto.class, wrapper);
```

**Comment by phoema** [comment]
+1

**Comment by yulichang** [comment]
1.4.10
