### ISSUE TITLE
调用selectJoinPage会报错

### ISSUE THREAD

**Issue by yangjun19950118** [yulichang/mybatis-plus-join#58]
Cannot invoke "com.github.yulichang.wrapper.segments.SelectCache.getColumn()" because the return value of "com.github.yulichang.wrapper.MPJAbstractLambdaWrapper.getCache(com.baomidou.mybatisplus.core.toolkit.support.SFunction)" is null]

**Comment by bbstone101** [comment]
遇到同样问题，等待解答中。。。

**Comment by yulichang** [comment]
用最新版试一下
