### ISSUE TITLE
两个不同的参数join同一张表

### ISSUE THREAD

**Issue by wen-carl** [yulichang/mybatis-plus-join#6]
比如一张表里面有：createUser，updateUser两个参数都需要join User表就会报错，好像没找到解决办法？

**Comment by wendiaoxu** [comment]
同问题

**Comment by LouisLiu00** [comment]
同问题，请问怎么解决的？

**Comment by LouisLiu00** [comment]
试试这样，同一个表关联多个字段：https://gitee.com/best_handsome/mybatis-plus-join/wikis/leftJoin?sort_id=3496671

**Comment by yulichang** [comment]
最新版已支持，文档有
