### ISSUE TITLE
distinct不生效

### ISSUE THREAD

**Issue by AFAP** [yulichang/mybatis-plus-join#61]
return sysUserRoleService.listObjs(new MPJLambdaWrapper<SysUserRoleEntity>()
        .distinct()
        .select(SysRoleMenuEntity::getMenuId)
        .leftJoin(SysRoleMenuEntity.class, SysRoleMenuEntity::getRoleId, SysUserRoleEntity::getRoleId)
        .eq(SysUserRoleEntity::getUserId, userId), o -> (String) o
);
以上这个期望的【SELECT distinct   t1.menu_id FROM sys_user_role t LEFT JOIN sys_role_menu t1 ON (t1.role_id = t.role_id)  WHERE (t.user_id = "XXX")】，但是实际sql没有distinct

**Comment by YSM777** [comment]
请问下，联表查询如何实现SELECT COUNT(DISTINCT t.id ) 这个DISTINCT不知道在哪加

**Comment by YSM777** [comment]
请问下，联表查询如何实现SELECT COUNT(DISTINCT t.id ) 这个DISTINCT不知道在哪加 @yulichang

**Comment by shilohooo** [comment]
> 请问下，联表查询如何实现SELECT COUNT(DISTINCT t.id ) 这个DISTINCT不知道在哪加 @yulichang

同问~

**Comment by shilohooo** [comment]
最新版的写法可以参考官方文档：https://mybatisplusjoin.com/pages/core/lambda/select/selectFunc.html
