### ISSUE TITLE
[bug?] selectJoinCount 返回字段问题

### ISSUE THREAD

**Issue by thriving123** [yulichang/mybatis-plus-join#67]
在官网中，selectJoinCount返回是Integer，但是在springboot的包中返回的是Long类型，且在当成Long使用时提示无法将Integer转为Long
![image](https://github.com/yulichang/mybatis-plus-join/assets/60968400/7e2bce91-2f02-402f-a853-0d3852c9a310)

![image](https://github.com/yulichang/mybatis-plus-join/assets/60968400/c3034444-ad72-43d9-8aaf-2e099849f394)

**Comment by xiguangfeng** [comment]
同问

**Comment by yulichang** [comment]
升级版本
