### ISSUE TITLE
引入了mybatis-plus-join 就不能使用mybatis原来的xml映射了嘛

### ISSUE THREAD

**Issue by soaringai** [yulichang/mybatis-plus-join#71]
我发现在mapper 接口里面新增了方法，然后项目就启动不起来了，请问这个有解决方法吗

**Comment by zepingwong** [comment]
不会啊，启动不起来具体报什么错呀

**Comment by soaringai** [comment]
Error createing bean with name com.github.yulichang.autoconfigure.MybatisPLusJoinAutoConfiguration

**Comment by yulichang** [comment]
自定义sql注入器
https://mybatisplusjoin.com/pages/problem.html#%E8%87%AA%E5%AE%9A%E4%B9%89sql%E6%B3%A8%E5%85%A5%E5%99%A8
