### ISSUE TITLE
条件构造器构建BigDecimal对象报错

### ISSUE THREAD

**Issue by lutao043** [yulichang/mybatis-plus-join#74]
// 入参为空时 还会执行new BigDecimal(param.getOperateState())构造对象 导致报错
gt.eq(StringUtils.isNotBlank(param.getOperateState()),OrderInSeriesNoPoolBean::getOperateState,new BigDecimal(param.getOperateState()))    

        // 改成这样才行 mybatis-plus框架的条件构造器不会报错
        if (StringUtils.isNotBlank(param.getOperateState())){
            gt.eq(OrderInSeriesNoPoolBean::getOperateState,new BigDecimal(param.getOperateState()));
        }

**Comment by yulichang** [comment]
用func
https://mybatisplusjoin.com/pages/core/tj/tj.html#func
