### ISSUE TITLE
使用selectJoinList报 rg.apache.ibatis.binding.BindingException: Invalid bound statement (not found): com.***.**Mapper.selectJoinList

### ISSUE THREAD

**Issue by iAmCorey** [yulichang/mybatis-plus-join#81]
没有使用自定义sql注入器也没有使用自定义sqlSessionFactory，
使用的版本是
com.github.yulichang:mybatsi-plus-join-boot-starter:1.4.5 
com.baomidou:mybatis-plus:3.5.2。
应用启动日志有：com.github.yulichang.autoconfigure.MybatisPlusJoinAutoConfiguration - MPJSqlInjector init
使用 List<DO> list = testMapper.selectList(wrapper) 没问题
使用 List<DTO> list = testMapper.selectJoinList(DTO.class, wrapper)报 org.apache.ibatis.binding.BindingException: Invalid bound statement (not found): com.***.**Mapper.selectJoinList

**Comment by iAmCorey** [comment]
补充：改为selectJoinMaps也同样报错invalid bound

**Comment by Evan-Sukhoi** [comment]
学长好，请问这个问题解决了吗QAQ？写ooad遇到了一模一样的问题

**Comment by Evan-Sukhoi** [comment]
我是把mybatis-plus-join版本从1.2.7更新到了最新（1.4.6），问题就解决了（spring-boot-starter-parent版本3.1.4）

**Comment by wangzeyu135798** [comment]
多数据源的时候也会报statement (not found): com.***.**Mapper.selectJoinList错误，依赖什么版本都不行

**Comment by 5take2you0fly** [comment]
请问这个问题找到原因了吗？怎么解决的

**Comment by wangzeyu135798** [comment]
感觉只能单数据源用 我切到单数据源下就好了



---原始邮件---
发件人: ***@***.***&gt;
发送时间: 2023年10月24日(周二) 中午11:48
收件人: ***@***.***&gt;;
抄送: ***@***.******@***.***&gt;;
主题: Re: [yulichang/mybatis-plus-join] 使用selectJoinList报 rg.apache.ibatis.binding.BindingException: Invalid bound statement (not found): com.***.**Mapper.selectJoinList (Issue #81)




 
请问这个问题找到原因了吗？怎么解决的

**Comment by yulichang** [comment]
https://mybatisplusjoin.com/pages/problem.html#%E8%87%AA%E5%AE%9A%E4%B9%89sqlsessionfactory

**Comment by iAmCorey** [comment]
> 请问这个问题找到原因了吗？怎么解决的

没有 还是老老实实用mybatis plus写sql语句了
