### ISSUE TITLE
关于join添加条件的功能，现在只有joinAnd，其条件只有‘某字段=某值’，应该可以扩展其他不同的条件

### ISSUE THREAD

**Issue by loolau** [yulichang/mybatis-plus-join#85]
使用的版本是1.7.4-RELEASE，在给join添加条件限制时，发现只有joinAnd功能，源码中关键代码为
` sql.setStringValue(sql.getStringValue() + String.format(SqlExcerpt.AND.getSql(), column, StringUtils.quotaMark(val)));`
其中的SqlExcerpt.AND为枚举SqlExcerpt.AND(" AND %s = %s ", "AND")，在SqlExcerpt的枚举中，为条件判断的只有这这个等于条件，
可以增加扩展其他几种常用的不同的条件，如不等于，大于，小于等等。

**Comment by yulichang** [comment]
用的不是这个项目吧，我怎么看不懂
