### ISSUE TITLE
多数据源下，org.apache.ibatis.binding.BindingException: Invalid bound statement (not found)

### ISSUE THREAD

**Issue by wangzeyu135798** [yulichang/mybatis-plus-join#86]
org.apache.ibatis.binding.BindingException: Invalid bound statement (not found): com.github.yulichang.join.mapper.j.UserMapper.selectJoinList
多数据源的配置没有问题，mybatis-plus-join在但数据源也可以跑，但是把mybatis-plus-join放到多数据源下就总是报这个错，不知道该怎么解决。

**Comment by yulichang** [comment]
https://mybatisplusjoin.com/pages/problem.html#%E8%87%AA%E5%AE%9A%E4%B9%89sqlsessionfactory

**Comment by xpluto** [comment]
> https://mybatisplusjoin.com/pages/problem.html#%E8%87%AA%E5%AE%9A%E4%B9%89sqlsessionfactory

多数据源场景需要配置多个 SqlSessionFactory

**Comment by cct20152** [comment]
> 我也遇到了，多租户模式下，如果不用SqlSessionFactory，数据源切换不生效，如过使用SqlSessionFactory，则MyBatis-Plus-Join聊表查询无法使用。

这个最后有没有解决掉？

**Comment by UtopianPuppy** [comment]
> org.apache.ibatis.binding.BindingException: Invalid bound statement (not found): com.github.yulichang.join.mapper.j.UserMapper.selectJoinList 多数据源的配置没有问题，mybatis-plus-join在但数据源也可以跑，但是把mybatis-plus-join放到多数据源下就总是报这个错，不知道该怎么解决。

请问问题解决了吗，我是通过mybatis-plus的dynamic-database配置的多数据源，然后用mybatis-plus-join就会报这个错，目前没查到有什么可行的解决方案
