### ISSUE TITLE
UNION ALL  多表联合查询，入参错乱

### ISSUE THREAD

**Issue by whirzhangkh** [yulichang/mybatis-plus-join#87]
拼接SQL如下图：
![image](https://github.com/yulichang/mybatis-plus-join/assets/69671957/5fb3e658-dfa4-4d7e-8808-c6c57e8ca5bb)
但是生成的sql取如下：
UNION ALL   
SELECT count(accepting.id) AS count 
FROM opm_wom_details accepting   
WHERE  accepting.deleted='N'   AND (accepting.app_id = #{ew.wrapperMap.ew1.paramNameValuePairs.MPGENVAL1} AND accepting.order_status = #{ew.wrapperMap.ew1.paramNameValuePairs.MPGENVAL2} AND accepting.assignee_id = #{ew.wrapperMap.ew1.paramNameValuePairs.MPGENVAL3})  
UNION ALL   
SELECT count(progress.id) AS count FROM opm_wom_details progress   WHERE  progress.deleted='N'   AND (progress.app_id = #{ew.wrapperMap.ew2.paramNameValuePairs.MPGENVAL1} AND progress.order_status = #{ew.wrapperMap.ew2.paramNameValuePairs.MPGENVAL2} AND (progress.assignee_id = #{ew.paramNameValuePairs.MPGENVAL3} OR progress.helper_ids LIKE #{ew.paramNameValuePairs.MPGENVAL4}))  
UNION ALL   
SELECT count(follow.id) AS count FROM opm_wom_details follow   WHERE  follow.deleted='N'   AND (follow.app_id = #{ew.wrapperMap.ew3.paramNameValuePairs.MPGENVAL1} AND follow.order_status = #{ew.wrapperMap.ew3.paramNameValuePairs.MPGENVAL2} AND (follow.follower_id = #{ew.paramNameValuePairs.MPGENVAL3}))  )

第二个UNION ALL   sql中使用  and 拼接的语句 入参  明显错误
AND (progress.assignee_id = #{ew.paramNameValuePairs.MPGENVAL3} OR progress.helper_ids LIKE #{ew.paramNameValuePairs.MPGENVAL4}))

**Comment by yulichang** [comment]
用1.4.7.1
