### ISSUE TITLE
UNION参数错乱

### ISSUE THREAD

**Issue by yejiaaqi** [yulichang/mybatis-plus-join#88]
当使用.leftJoin(UserAddressDO.class, on -> on
                        .eq(UserAddressDO::getUserId, UserDO::getId)
                        .eq(UserAddressDO::getId, UserDO::getId))多条件是依然会出现参数错乱，不使用不会

**Comment by yulichang** [comment]
有完整代码吗

**Comment by yejiaaqi** [comment]
private MPJBaseJoin<TRooms> synthesisWrapper(SynthesisRoomDTO synthesisRoomDTO) {
        MPJLambdaWrapper<TRooms> friendsWrapper = JoinWrappers.lambda(TRooms.class)
                .disableSubLogicDel()
                .leftJoin(TUserFriends.class, on -> on
                        .eq(TUserFriends::getRoomId, TRooms::getRoomId)
                        .eq(TRooms::getType, "3")
                )
                .isNotNull(TUserFriends::getPkId)
                .eq(TUserFriends::getDeleteFlag, CommonConstant.NO_DELETE_FLAG)
                .leftJoin(TUsers.class, TUsers::getUserId, TUserFriends::getFriendId)
                .leftJoin(TMessages.class, TMessages::getMsgId, TRooms::getActiveMsg)
                .selectAs(TUsers::getAvatarUrl, "avatar")
                .select("null as name")
                .selectAs(TUsers::getNickName, "nickname")
                .select(TUserFriends::getRemarkName)
                .selectAs(TMessages::getCreatedTime, "activeTime")
                .selectAs(TMessages::getContent, "msgContent")
                .selectAs(TMessages::getType, "msgType")
                .selectAs(TRooms::getType, "type")
                .selectAs(TRooms::getRoomId, "roomId")
                .selectAs(TUserFriends::getFriendId, "friendId")
                .select("null as groupId");
        MPJLambdaWrapper<TRooms> groupsWrapper = JoinWrappers.lambda(TRooms.class)
                .disableSubLogicDel()
                .leftJoin(TUserGroups.class, on -> on
                        .eq(TUserGroups::getRoomId, TRooms::getRoomId)
                        .eq(TRooms::getType, "3")
                )
                .isNotNull(TUserGroups::getPkId)
                .eq(TUserGroups::getDeleteFlag, CommonConstant.NO_DELETE_FLAG)
                .leftJoin(TGroups.class, TGroups::getGroupId, TUserGroups::getGroupId)
                .leftJoin(TMessages.class, TMessages::getMsgId, TRooms::getActiveMsg)
                .leftJoin(TUsers.class, TUsers::getUserId, TMessages::getFromUid)
                .selectAs(TGroups::getAvatarList, "avatar")
                .selectAs(TGroups::getGroupName, "name")
                .selectAs(TUsers::getNickName, "nickname")
                .selectAs(TUserGroups::getRemark, "remarkName")
                .selectAs(TMessages::getCreatedTime, "activeTime")
                .selectAs(TMessages::getContent, "msgContent")
                .selectAs(TMessages::getType, "msgType")
                .selectAs(TRooms::getType, "type")
                .selectAs(TRooms::getRoomId, "roomId")
                .select("null as friendId")
                .select(TUserGroups::getGroupId);
        if (null == synthesisRoomDTO) {
            return friendsWrapper;
        }
        if (StrUtil.isNotEmpty(synthesisRoomDTO.getUserId())) {
            friendsWrapper.eq(TUserFriends::getUserId, synthesisRoomDTO.getUserId());
            groupsWrapper.eq(TUserGroups::getUserId, synthesisRoomDTO.getUserId());
        }
        if (ListUtil.isNotEmpty(synthesisRoomDTO.getBlacklist())) {
            friendsWrapper.notIn(TUserFriends::getUserId, synthesisRoomDTO.getBlacklist());
        }
        friendsWrapper.union(groupsWrapper);
        return friendsWrapper;

**Comment by yejiaaqi** [comment]
改成下面就没问题了MPJLambdaWrapper<TRooms> friendsWrapper = JoinWrappers.lambda(TRooms.class)
                .disableSubLogicDel()
                .leftJoin(TUserFriends.class, TUserFriends::getRoomId, TRooms::getRoomId)
                .eq(TRooms::getType, "3")
                .isNotNull(TUserFriends::getPkId)
                .eq(TUserFriends::getDeleteFlag, CommonConstant.NO_DELETE_FLAG)
                .leftJoin(TUsers.class, TUsers::getUserId, TUserFriends::getFriendId)
                .leftJoin(TMessages.class, TMessages::getMsgId, TRooms::getActiveMsg)
                .selectAs(TUsers::getAvatarUrl, "avatar")
                .select("null as name")
                .selectAs(TUsers::getNickName, "nickname")
                .select(TUserFriends::getRemarkName)
                .selectAs(TMessages::getCreatedTime, "activeTime")
                .selectAs(TMessages::getContent, "msgContent")
                .selectAs(TMessages::getType, "msgType")
                .selectAs(TRooms::getType, "type")
                .selectAs(TRooms::getRoomId, "roomId")
                .selectAs(TUserFriends::getFriendId, "friendId")
                .select("null as groupId");
        MPJLambdaWrapper<TRooms> groupsWrapper = JoinWrappers.lambda(TRooms.class)
                .disableSubLogicDel()
                .leftJoin(TUserGroups.class, TUserGroups::getRoomId, TRooms::getRoomId)
                .eq(TRooms::getType, "1")
                .isNotNull(TUserGroups::getPkId)
                .eq(TUserGroups::getDeleteFlag, CommonConstant.NO_DELETE_FLAG)
                .leftJoin(TGroups.class, TGroups::getGroupId, TUserGroups::getGroupId)
                .leftJoin(TMessages.class, TMessages::getMsgId, TRooms::getActiveMsg)
                .leftJoin(TUsers.class, TUsers::getUserId, TMessages::getFromUid)
                .selectAs(TGroups::getAvatarList, "avatar")
                .selectAs(TGroups::getGroupName, "name")
                .selectAs(TUsers::getNickName, "nickname")
                .selectAs(TUserGroups::getRemark, "remarkName")
                .selectAs(TMessages::getCreatedTime, "activeTime")
                .selectAs(TMessages::getContent, "msgContent")
                .selectAs(TMessages::getType, "msgType")
                .selectAs(TRooms::getType, "type")
                .selectAs(TRooms::getRoomId, "roomId")
                .select("null as friendId")
                .select(TUserGroups::getGroupId);
        if (null == synthesisRoomDTO) {
            return friendsWrapper;
        }
        if (StrUtil.isNotEmpty(synthesisRoomDTO.getUserId())) {
            friendsWrapper.eq(TUserFriends::getUserId, synthesisRoomDTO.getUserId());
            groupsWrapper.eq(TUserGroups::getUserId, synthesisRoomDTO.getUserId());
        }
        if (ListUtil.isNotEmpty(synthesisRoomDTO.getBlacklist())) {
            friendsWrapper.notIn(TUserFriends::getUserId, synthesisRoomDTO.getBlacklist());
        }
        friendsWrapper.union(groupsWrapper);
        return friendsWrapper;
    }

**Comment by yulichang** [comment]
试一下 1.4.7.1

**Comment by yejiaaqi** [comment]
好的

**Comment by yejiaaqi** [comment]
已解决，真棒
