### ISSUE TITLE
关联查询，两个对象中的属性名相同，会报错No typehandler found for property xxx

### ISSUE THREAD

**Issue by whx159** [yulichang/mybatis-plus-join#90]
当前使用版本(必填,否则不予处理)
1.4.5。新版本也是同样的问题

该问题是如何引起的？(确定最新版也有问题再提!!!)
关联查询，两个对象中的属性名相同，都使用了typeHandle。

重现步骤(如果有就写完整)
![image](https://github.com/yulichang/mybatis-plus-join/assets/30753601/45da7695-5faf-4836-93f5-97aa40f95e40)
![image](https://github.com/yulichang/mybatis-plus-join/assets/30753601/7a514f01-93b4-4432-8a66-a5d2017e41ed)

columnList中存在两个相同的字段ext，但是他们的类型时不一样的，fieldMap是当前对象的字段解析。所以在执行fieldMap.get(i.getColumProperty())时，对于不同类型的ext字段得到的结果都是一样的，在后续设置typeHandler时会有问题。在build时会触发报错
![image](https://github.com/yulichang/mybatis-plus-join/assets/30753601/a3c68eef-1d81-42d4-8afa-ed77aefd6baa)

报错信息
No typehandler found for property xxx

两个对象起不同的属性名可以解决，但是会改变原来的结构。
使用别名的方式需要每个字短单独写，过于麻烦。
有没有全局的解决方案

**Comment by yulichang** [comment]
没有
